name = "Rewrap"
uuid = "e37f04ce-ca06-4a96-b09f-ea39bec02b08"
version = "0.1.4"
authors = ["Anton Oresten <antonoresten@proton.com> and contributors"]

[workspace]
projects = ["test"]

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
EllipsisNotation = "1"
julia = "1.9"
